### ISSUE TITLE
Investigate ties and ranking movement indicators

### ISSUE THREAD

**Issue by devinlizardi** [devinlizardi/astro-rankings#6]
we're not sure if the rank down indicator is properly showing movement, in the example image below the 2nd place user was never first, so it's odd that it's showing he moved down

similarly, we need to think through how we show indicators when users have the same score as their neighbors, though this may be a database issue

![Image](https://github.com/user-attachments/assets/ee74e7d7-81f7-423c-97fb-e3c4d40c61f5)

**Comment by mrodz** [comment]
Hi @devinlizardi, I wrote the code for the ranking movement without any testing, so my algorithm may be incorrect. I can write unit tests when I get home and get this resolved hopefully by EOD 7/20

**Comment by devinlizardi** [comment]
@mrodz no rush, it may be worth writing out a few simple cases and testing against them but for now it's not a big priority 

we're more interested in the cards dungeon view atm

**Comment by Astro-Games** [comment]
![image](https://github.com/user-attachments/assets/06f1818c-406f-4e15-b875-35a20ac45891)
So Nayeon went from 6th to 5th, and then Alice went from 5th to 6th, but the indictators seem swapped

**Comment by mrodz** [comment]
Yes you are correct, I ran tests using the latest data (7/26) and found that indeed, the ranking movement indicator is flipped. Will fix it now.
